/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorklistRouteImport } from './routes/_app.worklist'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppCalendrierRouteImport } from './routes/_app.calendrier'
import { Route as AppAnalyseRouteImport } from './routes/_app.analyse'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppWorklistIdRouteImport } from './routes/_app.worklist.$id'
import { Route as AppHistoriqueExamensRouteImport } from './routes/_app.historique.examens'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorklistRoute = AppWorklistRouteImport.update({
  id: '/worklist',
  path: '/worklist',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendrierRoute = AppCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyseRoute = AppAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppWorklistIdRoute = AppWorklistIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorklistRoute,
} as any)
const AppHistoriqueExamensRoute = AppHistoriqueExamensRouteImport.update({
  id: '/historique/examens',
  path: '/historique/examens',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/analyse': typeof AppAnalyseRoute
  '/calendrier': typeof AppCalendrierRoute
  '/logs': typeof AppLogsRoute
  '/worklist': typeof AppWorklistRouteWithChildren
  '/historique/examens': typeof AppHistoriqueExamensRoute
  '/worklist/$id': typeof AppWorklistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/analyse': typeof AppAnalyseRoute
  '/calendrier': typeof AppCalendrierRoute
  '/logs': typeof AppLogsRoute
  '/worklist': typeof AppWorklistRouteWithChildren
  '/historique/examens': typeof AppHistoriqueExamensRoute
  '/worklist/$id': typeof AppWorklistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/analyse': typeof AppAnalyseRoute
  '/_app/calendrier': typeof AppCalendrierRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/worklist': typeof AppWorklistRouteWithChildren
  '/_app/historique/examens': typeof AppHistoriqueExamensRoute
  '/_app/worklist/$id': typeof AppWorklistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/analyse'
    | '/calendrier'
    | '/logs'
    | '/worklist'
    | '/historique/examens'
    | '/worklist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/analyse'
    | '/calendrier'
    | '/logs'
    | '/worklist'
    | '/historique/examens'
    | '/worklist/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/analyse'
    | '/_app/calendrier'
    | '/_app/logs'
    | '/_app/worklist'
    | '/_app/historique/examens'
    | '/_app/worklist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/worklist': {
      id: '/_app/worklist'
      path: '/worklist'
      fullPath: '/worklist'
      preLoaderRoute: typeof AppWorklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendrier': {
      id: '/_app/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AppCalendrierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyse': {
      id: '/_app/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AppAnalyseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/worklist/$id': {
      id: '/_app/worklist/$id'
      path: '/$id'
      fullPath: '/worklist/$id'
      preLoaderRoute: typeof AppWorklistIdRouteImport
      parentRoute: typeof AppWorklistRoute
    }
    '/_app/historique/examens': {
      id: '/_app/historique/examens'
      path: '/historique/examens'
      fullPath: '/historique/examens'
      preLoaderRoute: typeof AppHistoriqueExamensRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppWorklistRouteChildren {
  AppWorklistIdRoute: typeof AppWorklistIdRoute
}

const AppWorklistRouteChildren: AppWorklistRouteChildren = {
  AppWorklistIdRoute: AppWorklistIdRoute,
}

const AppWorklistRouteWithChildren = AppWorklistRoute._addFileChildren(
  AppWorklistRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyseRoute: typeof AppAnalyseRoute
  AppCalendrierRoute: typeof AppCalendrierRoute
  AppLogsRoute: typeof AppLogsRoute
  AppWorklistRoute: typeof AppWorklistRouteWithChildren
  AppHistoriqueExamensRoute: typeof AppHistoriqueExamensRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyseRoute: AppAnalyseRoute,
  AppCalendrierRoute: AppCalendrierRoute,
  AppLogsRoute: AppLogsRoute,
  AppWorklistRoute: AppWorklistRouteWithChildren,
  AppHistoriqueExamensRoute: AppHistoriqueExamensRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
