# Generated by Django 5.0.4 on 2026-06-18 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('Rétinographie', 'Rétinographie'), ('OCT', 'OCT'), ('Champ visuel', 'Champ visuel'), ('Angiographie', 'Angiographie')], default='Rétinographie', max_length=50)),
                ('date', models.DateField()),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Normal', 'Normal')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Interprété', 'Interprété')], default='En attente', max_length=20)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('modality_ip', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
