# Generated by Django 5.0.4 on 2026-06-21 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophtalmo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('examination_id', models.CharField(db_index=True, max_length=255)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('AI_GENERATED', 'AI Generated'), ('UNDER_REVIEW', 'Under Review'), ('SIGNED', 'Signed')], default='AI_GENERATED', max_length=20)),
                ('ai_content', models.TextField(blank=True, default='')),
                ('doctor_content', models.TextField(blank=True, default='')),
                ('final_content', models.TextField(blank=True, default='')),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_report_data', models.JSONField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_medical_reports', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_medical_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('content', models.TextField(blank=True, default='')),
                ('version_type', models.CharField(choices=[('AI', 'AI Generated'), ('DOCTOR', 'Doctor Edit'), ('SIGNED', 'Signed')], max_length=10)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ophtalmo.medicalreport')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('report', 'version_number')},
            },
        ),
    ]
