# Generated by Django 5.0.4 on 2026-06-25 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophtalmo', '0002_medicalreport_medicalreportversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date_assignation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(db_index=True, max_length=255)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('report_json', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
    ]
