# Generated by Django 5.0.4 on 2026-06-29 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophtalmo', '0006_doctornote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_reassigned_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='reassigned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
