# Generated by Django 5.0.4 on 2026-07-18 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_status_history(apps, schema_editor):
    Exam = apps.get_model('ophtalmo', 'Exam')
    ExamStatusHistory = apps.get_model('ophtalmo', 'ExamStatusHistory')
    now = django.utils.timezone.now()

    events = []
    for exam in Exam.objects.all().iterator():
        events.append(ExamStatusHistory(
            exam_id=exam.id,
            status='En attente',
            changed_at=exam.created_at,
        ))
        if exam.status != 'En attente':
            events.append(ExamStatusHistory(
                exam_id=exam.id,
                status=exam.status,
                changed_at=exam.updated_at,
            ))
        elif exam.is_reassigned_24h and exam.reassigned_from_id:
            events.append(ExamStatusHistory(
                exam_id=exam.id,
                status='En cours',
                changed_at=exam.updated_at,
            ))
            events.append(ExamStatusHistory(
                exam_id=exam.id,
                status='En attente',
                changed_at=now,
            ))

    ExamStatusHistory.objects.bulk_create(events, batch_size=1000)


def clear_status_history(apps, schema_editor):
    apps.get_model('ophtalmo', 'ExamStatusHistory').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ophtalmo', '0014_rename_dicom_modality_site_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Interprété', 'Interprété')], max_length=20)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ophtalmo.exam')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.RunPython(seed_status_history, clear_status_history),
    ]
