FROM projectmonai/monailabel:latest

RUN pip3 install --no-cache-dir \
    "numpy<2" \
    "opencv-python-headless<4.12" \
    "transformers<5" \
    segmentation_models_pytorch \
    tensorflow-cpu \
    h5py
