from django.urls import path
from . import views

urlpatterns = [
    path('api/exams/', views.exam_list, name='exam-list'),
    path('api/exams/stats/', views.exam_stats, name='exam-stats'),
    path('api/dmi/exams/', views.dmi_exam_upsert, name='dmi-exam-upsert'),
    path('api/dmi/exams/<str:numero_examen>/acquisition-dicom/', views.dmi_exam_acquisition_dicom, name='dmi-exam-acquisition-dicom'),
    path('api/dmi/exams/<str:numero_examen>/compte-rendu/', views.dmi_exam_compte_rendu, name='dmi-exam-compte-rendu'),
    path('api/dmi/exams/<str:numero_examen>/status/', views.dmi_exam_status, name='dmi-exam-status'),
    path('api/exams/sync-orthanc/', views.sync_orthanc, name='exam-sync-orthanc'),
    path('api/exams/orthanc-webhook/', views.orthanc_webhook, name='orthanc-webhook'),
    path('api/exams/monai-webhook/', views.monai_inference_webhook, name='monai-inference-webhook'),
    path('api/exams/composite-segmentation/', views.request_composite_segmentation, name='request-composite-segmentation'),
    path('api/exams/run-analysis/', views.run_analysis, name='run-analysis'),
    path('api/exams/classify-worklist/', views.classify_worklist, name='classify-worklist'),
    path('api/exams/distribuer/', views.distribuer_manuellement, name='distribuer-examens'),
    path('api/exams/mes-examens/', views.mes_examens, name='mes-examens'),
    path('api/exams/save-analysis/', views.save_analysis, name='save-analysis'),
    path('api/exams/segmentation-corrections/', views.save_segmentation_corrections, name='save-segmentation-corrections'),
    path('api/exams/dr-grade-correction/', views.save_dr_grade_correction, name='save-dr-grade-correction'),
    path('api/exams/dmla-correction/', views.save_dmla_correction, name='save-dmla-correction'),
    path('api/exams/analysis/', views.latest_analysis, name='latest-analysis'),
    path('api/exams/analysis-reports/', views.list_analysis_reports, name='list-analysis-reports'),
    path('api/exams/generate-report/', views.generate_report, name='generate-report'),
    path('api/exams/doctor-notes/', views.doctor_notes, name='doctor-notes'),
    path('api/exams/medical-reports/', views.medical_report_list, name='medical-report-list'),
    path('api/exams/medical-reports/<int:pk>/', views.medical_report_detail, name='medical-report-detail'),
    path('api/exams/medical-reports/<int:pk>/sign/', views.sign_medical_report, name='sign-medical-report'),
    path('api/exams/medical-reports/<int:pk>/versions/', views.list_report_versions, name='list-report-versions'),
    path('api/exams/medical-reports/<int:pk>/export-docx/', views.export_report_docx, name='export-report-docx'),
    path('api/exams/<int:pk>/', views.exam_detail, name='exam-detail'),
    path('api/exams/<int:pk>/terminer/', views.terminer_examen, name='terminer-examen'),
    path('api/medecins/disponibilite/', views.toggle_disponibilite, name='toggle-disponibilite'),
]
