# Generated by Django 5.0.4 on 2026-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='charge_actuelle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profil',
            name='is_disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='region_affectation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
